### PR TITLE
Add The Geeko Dark Plus Theme

### PR DESCRIPTION
**Pull request by chankruze**
A dark theme inspired from VS Code default Dark+ theme.

Signed-off-by: chankruze <chankruze@gmail.com>

### CODE REVIEW

**Comment by lucasvieites** [comment]
I was just checking this theme and found you have a typo in geeko-dark-plus.conf:
name=Geeko Drak+

**Comment by chankruze** [comment]
That's not a typo ;)

Inspired from this:
Screenshot from 2020-01-04 18-13-57

Looks like this:
Screenshot from 2020-01-04 18-15-17

**Comment by chankruze** [comment]
Thanks for the review, appreciate that !

Actually my keyboard don't register key `a` or register later ;(

**Comment by chankruze** [comment]
Closing due to inactivity.

**Pull request closed without merging**
