### PR TITLE
Add Himbeere colorscheme

### PR DESCRIPTION
**Pull request by commenthol**

### CODE REVIEW

**Comment by codebrainz** [comment]
Added in d29e1717b1fa5f0c793e811c3c456cc88a49c356. Thanks!

**Comment by codebrainz** [comment]
I don't often use dark themes, unless my eyes are really tired, but this is my new first choice for that :)  Nice work.

**Comment by codebrainz** [comment]
@commenthol in my local copy I changed this:

```diff
-current_line=;#000;true
+current_line=;#2C2D2F;true
```

Do you like it? I felt the black active line was to stark of change from rest of theme.

**Comment by commenthol** [comment]
Thanks for liking and the merging.
The `current-line` change also looks good to me. 
My initial intention was to have max. contrast while typing.
But to be honest the lighter line fits better to the theme as you say. 
So feel free to change.

**Pull request closed without merging**
